### ISSUE TITLE
Basic Blocks: jump tables + variable flow succession

### ISSUE THREAD

**Issue by riidefi** [terorie/ppc750cl#11]
Each basic block should keep track of blocks that flow into it (predecessors) and blocks that flow out of it (successors). With this information we have a CFG.

In most cases, a basic block has two successors (branch target and fallthrough). However, when a jump table is emitted, a basic block can have n successors.

This issue tracks the jump table, variable case.

Depends on #9
Depends on #13

**Comment by riidefi** [comment]
Do we have any framework for detecting data references right now?

**Comment by terorie** [comment]
Duplicated by #26.
