### ISSUE TITLE
Python bindings

### ISSUE THREAD

**Issue by terorie** [terorie/ppc750cl#4]
The end goal of this project is being able to use it in Python infrastructure as a drop-in replacement for capstone.

**Comment by terorie** [comment]
Bindings mostly done. Still need to publish to pypi.

**Comment by terorie** [comment]
Concerns from Rii:
- Want offset, size on `disasm_iter`
- Want `dict()`, `dir()` on `Ins` for available fields

**Comment by riidefi** [comment]
- Add something like this
```rs
    #[getter]
    fn opcode_name(&self) -> PyResult<String> {
        Ok(self.0.op.to_string())
    }
```
- Fix field access

**Comment by terorie** [comment]
@riidefi Opcode name can now be retrieved

```
>>> import ppc750cl
>>> ppc750cl.Ins(addr=0x80006969, code=0x10400420).opcode
'ps_merge00'
```

Field access is still unsupported (has been removed in 0.2.0 but will come back)
